import { Goat, Expert, Debate, Domain, Era, User, Category } from '@/types/goat';

export const categories: Category[] = [
  {
    id: 'nba',
    slug: 'nba',
    name: 'NBA',
    domain: 'sports',
    description: 'The greatest basketball players in history.',
    icon: '🏀',
    colorTheme: '#1d428a',
    trendingGoats: [],
  },
  {
    id: 'football',
    slug: 'football',
    name: 'Football',
    domain: 'sports',
    description: 'The greatest football (soccer) players of all time.',
    icon: '⚽',
    colorTheme: '#4caf50',
    trendingGoats: [],
  },
  {
    id: 'rap',
    slug: 'rap',
    name: 'Rap (Music)',
    domain: 'music',
    description: 'The greatest lyricists and performers in hip-hop.',
    icon: '🎤',
    colorTheme: '#000000',
    trendingGoats: [],
  }
];

export const goats: Goat[] = [
  {
    id: 'michael-jordan',
    name: 'Michael Jordan',
    nickname: 'His Airness',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['1980s', '1990s'],
    region: 'North America',
    image: '/images/jordan_legend.png',
    country: 'USA',
    overallScore: 98.7,
    stats: {
      achievements: 99,
      influence: 98,
      awards: 100,
      longevity: 95,
      impact: 99,
      legacy: 100,
    },
    achievements: ['6x NBA Champion', '5x MVP', '6x Finals MVP', '14x All-Star', '10x Scoring Champion'],
    bio: 'Michael Jeffrey Jordan, also known as MJ, is widely considered the greatest basketball player of all time.',
    expertVotes: 15420,
    fanVotes: 2453000,
    trending: true,
    rank: 1,
    historicalRankings: [
      { year: 2020, rank: 1 },
      { year: 2021, rank: 1 },
      { year: 2022, rank: 1 },
      { year: 2023, rank: 1 },
    ],
  },
  {
    id: 'lebron-james',
    name: 'LeBron James',
    nickname: 'King James',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['2000s', '2010s', '2020s'],
    region: 'North America',
    image: '/images/lebron_legend.png',
    country: 'USA',
    overallScore: 97.8,
    stats: {
      achievements: 98,
      influence: 97,
      awards: 99,
      longevity: 100,
      impact: 98,
      legacy: 98,
    },
    achievements: ['4x NBA Champion', '4x MVP', '4x Finals MVP', '20x All-Star', 'All-Time Scoring Leader'],
    bio: 'LeBron Raymone James Sr. is an American professional basketball player for the Los Angeles Lakers of the NBA.',
    expertVotes: 14800,
    fanVotes: 2800000,
    trending: true,
    rank: 2,
  },
  {
    id: 'lionel-messi',
    name: 'Lionel Messi',
    nickname: 'La Pulga',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['2000s', '2010s', '2020s'],
    region: 'South America',
    image: '/images/messi_legend.png',
    country: 'Argentina',
    overallScore: 97.2,
    stats: {
      achievements: 98,
      influence: 96,
      awards: 100,
      longevity: 97,
      impact: 95,
      legacy: 96,
    },
    achievements: ['8x Ballon d\'Or', 'World Cup Winner', '4x Champions League', '10x La Liga'],
    bio: 'Lionel Andrés Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time.',
    expertVotes: 13800,
    fanVotes: 3200000,
    trending: true,
    rank: 1,
    historicalRankings: [
      { year: 2020, rank: 5 },
      { year: 2021, rank: 4 },
      { year: 2022, rank: 3 },
      { year: 2023, rank: 3 },
    ],
  },
  {
    id: 'cristiano-ronaldo',
    name: 'Cristiano Ronaldo',
    nickname: 'CR7',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['2000s', '2010s', '2020s'],
    region: 'Europe',
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80',
    country: 'Portugal',
    overallScore: 96.5,
    stats: {
      achievements: 97,
      influence: 100,
      awards: 98,
      longevity: 98,
      impact: 96,
      legacy: 97,
    },
    achievements: ['5x Ballon d\'Or', '5x Champions League', 'Euro 2016 Winner', 'All-Time Top Scorer'],
    bio: 'Cristiano Ronaldo dos Santos Aveiro is a Portuguese professional footballer who plays as a forward for and captains both Saudi Pro League club Al Nassr and the Portugal national team.',
    expertVotes: 13200,
    fanVotes: 3500000,
    trending: true,
    rank: 2,
  }
];

// Update trending goats in categories
categories[0].trendingGoats = [goats[0], goats[1]];
categories[1].trendingGoats = [goats[2], goats[3]];

export const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Sarah Mitchell',
    title: 'Sports Historian, ESPN',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    specialty: 'sports',
  },
  {
    id: '2',
    name: 'Prof. James Wilson',
    title: 'Music Critic, Rolling Stone',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    specialty: 'music',
  },
];

export const debates: Debate[] = [
  {
    id: 'jordan-vs-lebron',
    title: 'The NBA GOAT: Jordan vs LeBron',
    goat1: goats[0],
    goat2: goats[1],
    votes1: 54320,
    votes2: 48750,
    comments: 12500,
    trending: true,
    arguments: [
      {
        id: 'a1',
        userId: 'u1',
        userName: 'John Analyst',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
        content: 'Jordan\'s 6-0 Finals record and cultural impact are unmatched.',
        type: 'pro',
        upvotes: 1200,
        downvotes: 45,
        createdAt: new Date('2024-01-10'),
      },
      {
        id: 'a2',
        userId: 'u2',
        userName: 'LeBron Fan',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leo',
        content: 'LeBron\'s longevity, all-around game, and total stats make him the GOAT.',
        type: 'pro',
        upvotes: 1100,
        downvotes: 80,
        createdAt: new Date('2024-01-11'),
      },
    ],
    aiSummary: 'While Jordan dominates in peak dominance and finals record, LeBron leads in longevity and total statistics.',
    strongestArguments: {
      pro: '6-0 in Finals, cultural impact.',
      con: 'Longevity, all-around statistical dominance.',
    },
  },
];

export const currentUser: User = {
  id: 'u1',
  name: 'John Champion',
  email: 'john@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  influenceWeight: 1.5,
  votesCount: 42,
  debatesJoined: 12,
  accuracyScore: 88,
  achievements: ['Early Adopter', 'Top Contributor'],
  badges: [
    { id: 'b1', name: 'Analyst', description: 'Voted with 80%+ accuracy vs experts', icon: '📊', unlockedAt: new Date() },
    { id: 'b2', name: 'Historian', description: 'Voted in 5+ different eras', icon: '📜', unlockedAt: new Date() },
  ],
  contributionPoints: 1250,
  level: 42,
  role: 'admin',
};

export const domains: { value: Domain; label: string; icon: string }[] = [
  { value: 'sports', label: 'Sports', icon: '🏆' },
  { value: 'music', label: 'Music', icon: '🎵' },
  { value: 'politics', label: 'Politics', icon: '🏛️' },
  { value: 'entertainment', label: 'Entertainment', icon: '🎬' },
  { value: 'science', label: 'Science', icon: '🔬' },
  { value: 'culture', label: 'Culture', icon: '🌍' },
];

export const eras: Era[] = ['1900s', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
