import { Goat, Expert, Debate, Domain, Era, User, Category } from '@/types/goat';

export const categories: Category[] = [
  {
    id: 'nba',
    slug: 'nba',
    name: 'NBA',
    domain: 'sports',
    description: 'The greatest basketball players in history.',
    icon: '🏀',
    colorTheme: '#1d428a',
    trendingGoats: [],
  },
  {
    id: 'football',
    slug: 'football',
    name: 'Football',
    domain: 'sports',
    description: 'The greatest football (soccer) players of all time.',
    icon: '⚽',
    colorTheme: '#4caf50',
    trendingGoats: [],
  },
  {
    id: 'rap',
    slug: 'rap',
    name: 'Rap (Music)',
    domain: 'music',
    description: 'The greatest lyricists and performers in hip-hop.',
    icon: '🎤',
    colorTheme: '#000000',
    trendingGoats: [],
  }
];

export const goats: Goat[] = [
  {
    id: 'michael-jordan',
    name: 'Michael Jordan',
    nickname: 'His Airness',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['1980s', '1990s'],
    region: 'North America',
    image: '/images/jordan_legend.png',
    country: 'USA',
    overallScore: 98.7,
    stats: {
      achievements: 99,
      influence: 98,
      awards: 100,
      longevity: 95,
      impact: 99,
      legacy: 100,
    },
    achievements: ['6x NBA Champion', '5x MVP', '6x Finals MVP', '14x All-Star', '10x Scoring Champion'],
    bio: 'Michael Jeffrey Jordan, also known as MJ, is widely considered the greatest basketball player of all time.',
    expertVotes: 15420,
    fanVotes: 2453000,
    trending: true,
    rank: 1,
    historicalRankings: [
      { year: 2020, rank: 1 },
      { year: 2021, rank: 1 },
      { year: 2022, rank: 1 },
      { year: 2023, rank: 1 },
    ],
  },
  {
    id: 'lebron-james',
    name: 'LeBron James',
    nickname: 'King James',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['2000s', '2010s', '2020s'],
    region: 'North America',
    image: '/images/lebron_legend.png',
    country: 'USA',
    overallScore: 97.8,
    stats: {
      achievements: 98,
      influence: 97,
      awards: 99,
      longevity: 100,
      impact: 98,
      legacy: 98,
    },
    achievements: ['4x NBA Champion', '4x MVP', '4x Finals MVP', '20x All-Star', 'All-Time Scoring Leader'],
    bio: 'LeBron Raymone James Sr. is an American professional basketball player for the Los Angeles Lakers of the NBA.',
    expertVotes: 14800,
    fanVotes: 2800000,
    trending: true,
    rank: 2,
  },
  {
    id: 'kobe-bryant',
    name: 'Kobe Bryant',
    nickname: 'Black Mamba',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['1990s', '2000s', '2010s'],
    region: 'North America',
    image: '/images/kobe_legend.png',
    country: 'USA',
    overallScore: 96.8,
    stats: {
      achievements: 97,
      influence: 99,
      awards: 96,
      longevity: 98,
      impact: 99,
      legacy: 100,
    },
    achievements: ['5x NBA Champion', '1x MVP', '2x Finals MVP', '18x All-Star', '4x All-Star MVP'],
    bio: 'Kobe Bean Bryant was an American professional basketball player. A shooting guard, he spent his entire 20-year career with the Los Angeles Lakers in the NBA.',
    expertVotes: 13500,
    fanVotes: 3100000,
    trending: true,
    rank: 3,
  },
  {
    id: 'kareem-abdul-jabbar',
    name: 'Kareem Abdul-Jabbar',
    nickname: 'Cap',
    categoryId: 'nba',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['1960s', '1970s', '1980s'],
    region: 'North America',
    image: '/images/kareem_legend.png',
    country: 'USA',
    overallScore: 96.5,
    stats: {
      achievements: 99,
      influence: 95,
      awards: 100,
      longevity: 100,
      impact: 94,
      legacy: 98,
    },
    achievements: ['6x NBA Champion', '6x MVP', '2x Finals MVP', '19x All-Star', 'All-Time Leading Scorer (Former)'],
    bio: 'Kareem Abdul-Jabbar is an American former professional basketball player who played 20 seasons in the NBA for the Milwaukee Bucks and the Los Angeles Lakers.',
    expertVotes: 14100,
    fanVotes: 1800000,
    trending: false,
    rank: 4,
  },
  {
    id: 'lionel-messi',
    name: 'Lionel Messi',
    nickname: 'La Pulga',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['2000s', '2010s', '2020s'],
    region: 'South America',
    image: '/images/messi_legend.png',
    country: 'Argentina',
    overallScore: 97.2,
    stats: {
      achievements: 98,
      influence: 96,
      awards: 100,
      longevity: 97,
      impact: 95,
      legacy: 96,
    },
    achievements: ['8x Ballon d\'Or', 'World Cup Winner', '4x Champions League', '10x La Liga'],
    bio: 'Lionel Andrés Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time.',
    expertVotes: 13800,
    fanVotes: 3200000,
    trending: true,
    rank: 1,
    historicalRankings: [
      { year: 2020, rank: 5 },
      { year: 2021, rank: 4 },
      { year: 2022, rank: 3 },
      { year: 2023, rank: 3 },
    ],
  },
  {
    id: 'cristiano-ronaldo',
    name: 'Cristiano Ronaldo',
    nickname: 'CR7',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['2000s', '2010s', '2020s'],
    region: 'Europe',
    image: '/images/ronaldo_legend.png',
    country: 'Portugal',
    overallScore: 96.5,
    stats: {
      achievements: 97,
      influence: 100,
      awards: 98,
      longevity: 98,
      impact: 96,
      legacy: 97,
    },
    achievements: ['5x Ballon d\'Or', '5x Champions League', 'Euro 2016 Winner', 'All-Time Top Scorer'],
    bio: 'Cristiano Ronaldo dos Santos Aveiro is a Portuguese professional footballer who plays as a forward for and captains both Saudi Pro League club Al Nassr and the Portugal national team.',
    expertVotes: 13200,
    fanVotes: 3500000,
    trending: true,
    rank: 2,
  },
  {
    id: 'pele',
    name: 'Pelé',
    nickname: 'O Rei',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['1950s', '1960s', '1970s'],
    region: 'South America',
    image: '/images/pele_legend.png',
    country: 'Brazil',
    overallScore: 98.1,
    stats: {
      achievements: 99,
      influence: 99,
      awards: 95,
      longevity: 94,
      impact: 100,
      legacy: 100,
    },
    achievements: ['3x World Cup Winner', 'FIFA Player of the Century', '1279 Goals', 'Santos Legend'],
    bio: 'Edson Arantes do Nascimento, better known as Pelé, was a Brazilian professional footballer who played as a forward. He is regarded as one of the greatest players of all time.',
    expertVotes: 15100,
    fanVotes: 2100000,
    trending: false,
    rank: 3,
  },
  {
    id: 'diego-maradona',
    name: 'Diego Maradona',
    nickname: 'El Pibe de Oro',
    categoryId: 'football',
    domain: 'sports',
    subdomain: 'Football',
    era: ['1970s', '1980s', '1990s'],
    region: 'South America',
    image: '/images/maradona_legend.png',
    country: 'Argentina',
    overallScore: 97.5,
    stats: {
      achievements: 96,
      influence: 98,
      awards: 94,
      longevity: 92,
      impact: 100,
      legacy: 99,
    },
    achievements: ['1986 World Cup Winner', 'FIFA Player of the Century', 'Napoli Legend', 'Goal of the Century'],
    bio: 'Diego Armando Maradona was an Argentine professional football player and manager. Widely regarded as one of the greatest players in the history of the sport.',
    expertVotes: 14500,
    fanVotes: 2300000,
    trending: false,
    rank: 4,
  },
  {
    id: 'tupac-shakur',
    name: 'Tupac Shakur',
    nickname: '2Pac',
    categoryId: 'rap',
    domain: 'music',
    subdomain: 'Rap',
    era: ['1990s'],
    region: 'North America',
    image: '/images/tupac_legend.png',
    country: 'USA',
    overallScore: 98.5,
    stats: {
      achievements: 95,
      influence: 100,
      awards: 92,
      longevity: 85,
      impact: 100,
      legacy: 100,
    },
    achievements: ['75 Million Records Sold', 'Rock and Roll Hall of Fame', 'Cultural Icon', 'Poet'],
    bio: 'Tupac Amaru Shakur, also known as 2Pac and Makaveli, was an American rapper, songwriter, and actor. He is widely considered one of the most influential rappers of all time.',
    expertVotes: 14900,
    fanVotes: 3800000,
    trending: true,
    rank: 1,
  },
  {
    id: 'notorious-big',
    name: 'The Notorious B.I.G.',
    nickname: 'Biggie Smalls',
    categoryId: 'rap',
    domain: 'music',
    subdomain: 'Rap',
    era: ['1990s'],
    region: 'North America',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80',
    country: 'USA',
    overallScore: 97.9,
    stats: {
      achievements: 94,
      influence: 98,
      awards: 93,
      longevity: 80,
      impact: 99,
      legacy: 99,
    },
    achievements: ['King of New York', 'Rock and Roll Hall of Fame', 'Diamond Album', 'Lyrical Genius'],
    bio: 'Christopher George Latore Wallace, better known as The Notorious B.I.G., Biggie Smalls, or simply Biggie, was an American rapper and songwriter.',
    expertVotes: 14600,
    fanVotes: 3400000,
    trending: true,
    rank: 2,
  },
  {
    id: 'jay-z',
    name: 'Jay-Z',
    nickname: 'Hova',
    categoryId: 'rap',
    domain: 'music',
    subdomain: 'Rap',
    era: ['1990s', '2000s', '2010s', '2020s'],
    region: 'North America',
    image: 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?w=800&q=80',
    country: 'USA',
    overallScore: 97.4,
    stats: {
      achievements: 100,
      influence: 99,
      awards: 100,
      longevity: 100,
      impact: 97,
      legacy: 98,
    },
    achievements: ['24 Grammy Awards', '14 #1 Albums', 'Billionaire', 'Songwriters Hall of Fame'],
    bio: 'Shawn Corey Carter, known professionally as Jay-Z, is an American rapper, record producer, and entrepreneur.',
    expertVotes: 14200,
    fanVotes: 2900000,
    trending: false,
    rank: 3,
  },
  {
    id: 'nas',
    name: 'Nas',
    nickname: 'Nasty Nas',
    categoryId: 'rap',
    domain: 'music',
    subdomain: 'Rap',
    era: ['1990s', '2000s', '2010s', '2020s'],
    region: 'North America',
    image: 'https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=800&q=80',
    country: 'USA',
    overallScore: 96.9,
    stats: {
      achievements: 93,
      influence: 97,
      awards: 94,
      longevity: 98,
      impact: 96,
      legacy: 98,
    },
    achievements: ['Illmatic (Best Rap Album)', 'Grammy Winner', 'Storytelling King', 'Library of Congress'],
    bio: 'Nasir bin Olu Dara Jones, better known as Nas, is an American rapper. Rooted in East Coast hip hop, he is regarded as one of the greatest rappers of all time.',
    expertVotes: 13900,
    fanVotes: 2600000,
    trending: false,
    rank: 4,
  }
];

// Update trending goats in categories
categories[0].trendingGoats = [goats[0], goats[1], goats[2]];
categories[1].trendingGoats = [goats[4], goats[5], goats[6]];
categories[2].trendingGoats = [goats[8], goats[9]];

export const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Sarah Mitchell',
    title: 'Sports Historian, ESPN',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    specialty: 'sports',
  },
  {
    id: '2',
    name: 'Prof. James Wilson',
    title: 'Music Critic, Rolling Stone',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    specialty: 'music',
  },
];

export const debates: Debate[] = [
  {
    id: 'jordan-vs-lebron',
    title: 'The NBA GOAT: Jordan vs LeBron',
    goat1: goats[0],
    goat2: goats[1],
    votes1: 54320,
    votes2: 48750,
    comments: 12500,
    trending: true,
    arguments: [
      {
        id: 'a1',
        userId: 'u1',
        userName: 'John Analyst',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
        content: 'Jordan\'s 6-0 Finals record and cultural impact are unmatched.',
        type: 'pro',
        upvotes: 1200,
        downvotes: 45,
        createdAt: new Date('2024-01-10'),
      },
      {
        id: 'a2',
        userId: 'u2',
        userName: 'LeBron Fan',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leo',
        content: 'LeBron\'s longevity, all-around game, and total stats make him the GOAT.',
        type: 'pro',
        upvotes: 1100,
        downvotes: 80,
        createdAt: new Date('2024-01-11'),
      },
    ],
    aiSummary: 'While Jordan dominates in peak dominance and finals record, LeBron leads in longevity and total statistics.',
    strongestArguments: {
      pro: '6-0 in Finals, cultural impact.',
      con: 'Longevity, all-around statistical dominance.',
    },
  },
];

export const currentUser: User = {
  id: 'u1',
  name: 'John Champion',
  email: 'john@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  influenceWeight: 1.5,
  votesCount: 42,
  debatesJoined: 12,
  accuracyScore: 88,
  achievements: ['Early Adopter', 'Top Contributor'],
  badges: [
    { id: 'b1', name: 'Analyst', description: 'Voted with 80%+ accuracy vs experts', icon: '📊', unlockedAt: new Date() },
    { id: 'b2', name: 'Historian', description: 'Voted in 5+ different eras', icon: '📜', unlockedAt: new Date() },
  ],
  contributionPoints: 1250,
  level: 42,
  role: 'admin',
};

export const domains: { value: Domain; label: string; icon: string }[] = [
  { value: 'sports', label: 'Sports', icon: '🏆' },
  { value: 'music', label: 'Music', icon: '🎵' },
  { value: 'politics', label: 'Politics', icon: '🏛️' },
  { value: 'entertainment', label: 'Entertainment', icon: '🎬' },
  { value: 'science', label: 'Science', icon: '🔬' },
  { value: 'culture', label: 'Culture', icon: '🌍' },
];

export const eras: Era[] = ['1900s', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
