import { Goat, Expert, Debate, Domain, Era } from '@/types/goat';

export const goats: Goat[] = [
  {
    id: '1',
    name: 'Michael Jordan',
    nickname: 'His Airness',
    domain: 'sports',
    subdomain: 'Basketball',
    era: ['1980s', '1990s'],
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 98.7,
    stats: {
      achievements: 99,
      influence: 98,
      awards: 100,
      longevity: 95,
      impact: 99,
      legacy: 100,
    },
    achievements: ['6x NBA Champion', '5x MVP', '6x Finals MVP', '14x All-Star', '10x Scoring Champion'],
    bio: 'Michael Jeffrey Jordan, also known as MJ, is widely considered the greatest basketball player of all time.',
    expertVotes: 15420,
    fanVotes: 2453000,
    trending: true,
    rank: 1,
  },
  {
    id: '2',
    name: 'Muhammad Ali',
    nickname: 'The Greatest',
    domain: 'sports',
    subdomain: 'Boxing',
    era: ['1960s', '1970s', '1980s'],
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 97.5,
    stats: {
      achievements: 96,
      influence: 100,
      awards: 95,
      longevity: 94,
      impact: 100,
      legacy: 100,
    },
    achievements: ['3x World Heavyweight Champion', 'Olympic Gold Medalist', '56 Wins', 'Sports Illustrated Sportsman of the Century'],
    bio: 'Muhammad Ali was an American professional boxer, activist, and philanthropist, nicknamed "The Greatest".',
    expertVotes: 14200,
    fanVotes: 2120000,
    trending: true,
    rank: 2,
  },
  {
    id: '3',
    name: 'Lionel Messi',
    nickname: 'La Pulga',
    domain: 'sports',
    subdomain: 'Football',
    era: ['2000s', '2010s', '2020s'],
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&h=400&fit=crop',
    country: 'Argentina',
    overallScore: 97.2,
    stats: {
      achievements: 98,
      influence: 96,
      awards: 100,
      longevity: 97,
      impact: 95,
      legacy: 96,
    },
    achievements: ['8x Ballon d\'Or', 'World Cup Winner', '4x Champions League', '10x La Liga'],
    bio: 'Lionel Andrés Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time.',
    expertVotes: 13800,
    fanVotes: 3200000,
    trending: true,
    rank: 3,
  },
  {
    id: '4',
    name: 'Michael Jackson',
    nickname: 'King of Pop',
    domain: 'music',
    subdomain: 'Pop',
    era: ['1970s', '1980s', '1990s', '2000s'],
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 96.8,
    stats: {
      achievements: 98,
      influence: 100,
      awards: 97,
      longevity: 92,
      impact: 100,
      legacy: 100,
    },
    achievements: ['13 Grammy Awards', 'Best-selling album ever (Thriller)', 'Rock & Roll Hall of Fame', 'Over 400 million records sold'],
    bio: 'Michael Joseph Jackson was an American singer, songwriter, and dancer, dubbed the "King of Pop".',
    expertVotes: 12500,
    fanVotes: 2800000,
    trending: false,
    rank: 4,
  },
  {
    id: '5',
    name: 'Serena Williams',
    nickname: 'Queen of the Court',
    domain: 'sports',
    subdomain: 'Tennis',
    era: ['1990s', '2000s', '2010s', '2020s'],
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 95.4,
    stats: {
      achievements: 97,
      influence: 95,
      awards: 98,
      longevity: 96,
      impact: 94,
      legacy: 93,
    },
    achievements: ['23 Grand Slam Singles Titles', '4x Olympic Gold Medalist', '319 weeks at #1', 'Tennis Hall of Fame'],
    bio: 'Serena Jameka Williams is an American former professional tennis player, widely regarded as the greatest female tennis player of all time.',
    expertVotes: 11200,
    fanVotes: 1900000,
    trending: true,
    rank: 5,
  },
  {
    id: '6',
    name: 'Beyoncé',
    nickname: 'Queen Bey',
    domain: 'music',
    subdomain: 'R&B/Pop',
    era: ['1990s', '2000s', '2010s', '2020s'],
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 94.9,
    stats: {
      achievements: 95,
      influence: 97,
      awards: 99,
      longevity: 94,
      impact: 96,
      legacy: 92,
    },
    achievements: ['32 Grammy Awards', 'Most Grammy wins ever', 'Over 200 million records sold', 'TIME 100 Most Influential'],
    bio: 'Beyoncé Giselle Knowles-Carter is an American singer, songwriter, and businesswoman, one of the most acclaimed artists of the 21st century.',
    expertVotes: 10800,
    fanVotes: 2650000,
    trending: true,
    rank: 6,
  },
  {
    id: '7',
    name: 'Tom Brady',
    nickname: 'TB12',
    domain: 'sports',
    subdomain: 'American Football',
    era: ['2000s', '2010s', '2020s'],
    image: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=400&fit=crop',
    country: 'USA',
    overallScore: 94.6,
    stats: {
      achievements: 99,
      influence: 90,
      awards: 98,
      longevity: 100,
      impact: 88,
      legacy: 95,
    },
    achievements: ['7x Super Bowl Champion', '5x Super Bowl MVP', '3x NFL MVP', '15x Pro Bowl'],
    bio: 'Thomas Edward Patrick Brady Jr. is a former American football quarterback who is widely considered the greatest NFL player of all time.',
    expertVotes: 10500,
    fanVotes: 1750000,
    trending: false,
    rank: 7,
  },
  {
    id: '8',
    name: 'Albert Einstein',
    nickname: 'Father of Modern Physics',
    domain: 'science',
    subdomain: 'Physics',
    era: ['1900s', '1950s'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    country: 'Germany',
    overallScore: 99.1,
    stats: {
      achievements: 100,
      influence: 100,
      awards: 95,
      longevity: 100,
      impact: 100,
      legacy: 100,
    },
    achievements: ['Nobel Prize in Physics', 'Theory of Relativity', 'E=mc²', 'TIME Person of the Century'],
    bio: 'Albert Einstein was a German-born theoretical physicist who developed the theory of relativity, one of the pillars of modern physics.',
    expertVotes: 16000,
    fanVotes: 1200000,
    trending: false,
    rank: 8,
  },
];

export const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Sarah Mitchell',
    title: 'Sports Historian, ESPN',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    specialty: 'sports',
  },
  {
    id: '2',
    name: 'Prof. James Wilson',
    title: 'Music Critic, Rolling Stone',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    specialty: 'music',
  },
  {
    id: '3',
    name: 'Dr. Emily Chen',
    title: 'Cultural Analyst, TIME',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    specialty: 'entertainment',
  },
];

export const debates: Debate[] = [
  {
    id: '1',
    title: 'The Ultimate GOAT: Jordan vs Messi',
    goat1: goats[0],
    goat2: goats[2],
    votes1: 54320,
    votes2: 48750,
    comments: 12500,
    trending: true,
  },
  {
    id: '2',
    title: 'Music Royalty: MJ vs Beyoncé',
    goat1: goats[3],
    goat2: goats[5],
    votes1: 42100,
    votes2: 39800,
    comments: 8900,
    trending: true,
  },
  {
    id: '3',
    title: 'Boxing vs Football: Ali vs Brady',
    goat1: goats[1],
    goat2: goats[6],
    votes1: 38500,
    votes2: 25600,
    comments: 6700,
    trending: false,
  },
];

export const domains: { value: Domain; label: string; icon: string }[] = [
  { value: 'sports', label: 'Sports', icon: '🏆' },
  { value: 'music', label: 'Music', icon: '🎵' },
  { value: 'politics', label: 'Politics', icon: '🏛️' },
  { value: 'entertainment', label: 'Entertainment', icon: '🎬' },
  { value: 'science', label: 'Science', icon: '🔬' },
];

export const eras: Era[] = ['1900s', '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
