"""Add fan voting system models

Revision ID: 0fa85757a722
Revises: aa5bb6099c36
Create Date: 2026-01-19 12:08:26.616826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa85757a722'
down_revision: Union[str, Sequence[str], None] = 'aa5bb6099c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trust_scores',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('engagement_level', sa.Integer(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trust_scores_id'), 'user_trust_scores', ['id'], unique=False)
    op.create_index(op.f('ix_user_trust_scores_user_id'), 'user_trust_scores', ['user_id'], unique=False)
    op.create_table('fan_vote_aggregates',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'category_id', name='_entity_category_aggregate_uc')
    )
    op.create_index(op.f('ix_fan_vote_aggregates_id'), 'fan_vote_aggregates', ['id'], unique=False)
    op.create_table('fan_votes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_id', 'category_id', name='_user_entity_category_uc')
    )
    op.create_index(op.f('ix_fan_votes_id'), 'fan_votes', ['id'], unique=False)
    op.create_index(op.f('ix_fan_votes_user_id'), 'fan_votes', ['user_id'], unique=False)
    op.create_table('vote_anomalies',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_anomalies_id'), 'vote_anomalies', ['id'], unique=False)
    op.create_table('fan_vote_versions',
    sa.Column('fan_vote_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fan_vote_id'], ['fan_votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fan_vote_versions_id'), 'fan_vote_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fan_vote_versions_id'), table_name='fan_vote_versions')
    op.drop_table('fan_vote_versions')
    op.drop_index(op.f('ix_vote_anomalies_id'), table_name='vote_anomalies')
    op.drop_table('vote_anomalies')
    op.drop_index(op.f('ix_fan_votes_user_id'), table_name='fan_votes')
    op.drop_index(op.f('ix_fan_votes_id'), table_name='fan_votes')
    op.drop_table('fan_votes')
    op.drop_index(op.f('ix_fan_vote_aggregates_id'), table_name='fan_vote_aggregates')
    op.drop_table('fan_vote_aggregates')
    op.drop_index(op.f('ix_user_trust_scores_user_id'), table_name='user_trust_scores')
    op.drop_index(op.f('ix_user_trust_scores_id'), table_name='user_trust_scores')
    op.drop_table('user_trust_scores')
    # ### end Alembic commands ###
