"""add_category_scoping

Revision ID: 701a851fb3b0
Revises: 3e1c941cd047
Create Date: 2026-01-21 11:08:20.820659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701a851fb3b0'
down_revision: Union[str, Sequence[str], None] = '3e1c941cd047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable
    op.add_column('categories', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('entities', sa.Column('category_id', sa.Uuid(), nullable=True))

    # 2. Backfill domain for categories
    op.execute("UPDATE categories SET domain = 'Sports' WHERE domain IS NULL")

    # 3. Backfill category_id for entities from subcategories
    op.execute("""
        UPDATE entities
        SET category_id = subcategories.category_id
        FROM subcategories
        WHERE entities.subcategory_id = subcategories.id
        AND entities.category_id IS NULL
    """)
    
    # 4. Backfill image_url if null (to satisfy NOT NULL constraint)
    op.execute("UPDATE entities SET image_url = 'https://images.unsplash.com/photo-1518770660439-4636190af475' WHERE image_url IS NULL")

    # 5. Set NOT NULL constraints
    op.alter_column('categories', 'domain', nullable=False)
    op.alter_column('entities', 'category_id', nullable=False)
    op.alter_column('entities', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # 6. Create indexes and FK
    op.create_index(op.f('ix_categories_domain'), 'categories', ['domain'], unique=False)
    op.create_index(op.f('ix_entities_category_id'), 'entities', ['category_id'], unique=False)
    op.create_foreign_key(None, 'entities', 'categories', ['category_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_category_id'), table_name='entities')
    op.alter_column('entities', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_column('entities', 'category_id')
    op.drop_index(op.f('ix_categories_domain'), table_name='categories')
    op.drop_column('categories', 'domain')
    # ### end Alembic commands ###
