"""Add expert voting system models

Revision ID: aa5bb6099c36
Revises: 9d4f8b54212f
Create Date: 2026-01-19 11:52:28.448770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5bb6099c36'
down_revision: Union[str, Sequence[str], None] = '9d4f8b54212f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_id'), 'experts', ['id'], unique=False)
    op.create_table('expert_audit_logs',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_audit_logs_id'), 'expert_audit_logs', ['id'], unique=False)
    op.create_table('expert_domains',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('expertise_level', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_domains_id'), 'expert_domains', ['id'], unique=False)
    op.create_table('expert_reputation_events',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('change_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_reputation_events_id'), 'expert_reputation_events', ['id'], unique=False)
    op.create_table('conflict_disclosures',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_disclosures_id'), 'conflict_disclosures', ['id'], unique=False)
    op.create_table('expert_votes',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('scoring_model_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_model_id'], ['scoring_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_votes_id'), 'expert_votes', ['id'], unique=False)
    op.create_table('expert_score_contributions',
    sa.Column('final_score_id', sa.UUID(), nullable=False),
    sa.Column('expert_vote_id', sa.UUID(), nullable=False),
    sa.Column('impact_weight', sa.Float(), nullable=False),
    sa.Column('contribution_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_vote_id'], ['expert_votes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_score_id'], ['final_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_score_contributions_id'), 'expert_score_contributions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_score_contributions_id'), table_name='expert_score_contributions')
    op.drop_table('expert_score_contributions')
    op.drop_index(op.f('ix_expert_votes_id'), table_name='expert_votes')
    op.drop_table('expert_votes')
    op.drop_index(op.f('ix_conflict_disclosures_id'), table_name='conflict_disclosures')
    op.drop_table('conflict_disclosures')
    op.drop_index(op.f('ix_expert_reputation_events_id'), table_name='expert_reputation_events')
    op.drop_table('expert_reputation_events')
    op.drop_index(op.f('ix_expert_domains_id'), table_name='expert_domains')
    op.drop_table('expert_domains')
    op.drop_index(op.f('ix_expert_audit_logs_id'), table_name='expert_audit_logs')
    op.drop_table('expert_audit_logs')
    op.drop_index(op.f('ix_experts_id'), table_name='experts')
    op.drop_table('experts')
    # ### end Alembic commands ###
